### ISSUE TITLE
|| (typeof(options) !== 'object'

### ISSUE THREAD

**Issue by Zarwlar** [Geksanit/Maket-resume#13]
Разве !options недостаточно?)

**Comment by Geksanit** [comment]
Раньше мне это помогало, уже не помню от чего)

**Comment by Geksanit** [comment]
Ах да, без этой проверки, если аргумент будет числом, то не получится подставить дефолтные значения в свойства объекта, т.к. его нет. Тут уж я не знаю какая принята культура переиспользования миксина.

**Comment by kinda-neat** [comment]
Тогда здесь на твое усмотрение, можешь закрывать а можешь отрефакторить)
