### ISSUE TITLE
Блок contact захардкожен

### ISSUE THREAD

**Issue by Zarwlar** [Geksanit/Maket-resume#17]
Для исправления нужно воспользоваться рекомендациями из предыдущих ишусов :)

**Comment by Geksanit** [comment]
Ну вроде сейчас стало лучше, но я не уверен что это окончательный вариант. Меня смущают ссылки и дополнительный миксин. Нужно ли получать аргумент в миксине contact и как их обрабатывать: как обьект, как массив обьектов, как массив массивов. 0_о
