### ISSUE TITLE
PixelPerfect

### ISSUE THREAD

**Issue by Zarwlar** [Geksanit/Maket-resume#19]
Скинь плз свой скриншот с макетом. Мой выглядит вот так, и на нём всё едет :(
![image](https://user-images.githubusercontent.com/26929933/33518340-e84503ac-d7c5-11e7-8fbd-360eeaae6001.png)

**Comment by Geksanit** [comment]
https://github.com/Geksanit/Maket-resume/blob/master/perfect%20pixel.jpg

**Comment by Zarwlar** [comment]
Это же просто макет?) Мне нужен скриншот того, как ты приклал макет к свой вёрстке, т.е. такой же, как скинул я)

**Comment by Geksanit** [comment]
![screen](https://user-images.githubusercontent.com/31949379/33712359-b9b90422-db79-11e7-8c56-5670bb65204b.JPG)

**Comment by Geksanit** [comment]
Я старался как мог))

**Comment by Zarwlar** [comment]
А где низ макета?)

**Comment by Geksanit** [comment]
Скриню ножницами )
![screen2](https://user-images.githubusercontent.com/31949379/33721396-7c5c09ec-db99-11e7-8de9-15c1dca29fe5.JPG)
