### ISSUE TITLE
Привести в порядок codestyl .less файлов

### ISSUE THREAD

**Issue by Zarwlar** [Geksanit/Maket-resume#25]
Посмотри в интернете code style для .less файлов и поправь в соответствии с ними) Отступы, пробелы между скобок и т.п.

**Comment by Geksanit** [comment]
вот [это](http://devdocs.magento.com/guides/v2.0/coding-standards/code-standard-less.html) ? но тут отступы 4 пробела, а у нас в стандартах 2. Над остальным работаю.

**Comment by Zarwlar** [comment]
Ага, например этот

**Comment by Geksanit** [comment]
Исправлять стиль придется очень долго...  сортировка свойств в алфавитном порядке, вручную.

**Comment by Zarwlar** [comment]
Не, это не нужно делать. Тебе стоит обратить внимание на пробелы между ){ и отступы в целом

**Comment by Geksanit** [comment]
Понял, я обычно группирую свойства, стилизация шрифтов\размеры и отступы\цвета.
