### ISSUE TITLE
Апостроф и кавычки

### ISSUE THREAD

**Issue by Zarwlar** [Geksanit/Maket-resume#26]
Сейчас они скачут от места к месту. Где-то используются апострофы, где-то — кавычки. Есть даже файл, где одновременно и то и другое используется :) Нужно унифицировать. Лучше использовать апострофы

**Comment by Geksanit** [comment]
В последних коммитах вроде исправил.
Но в pug атрибуты тэгов в двойных кавычках, как написано в стандартах.
П.С. ишьюсы только сегодня увидел, когда мержить начал )
