### ISSUE TITLE
Заменить все пиксели на rem em или %

### ISSUE THREAD

**Issue by Burize** [Geksanit/Maket-resume#3]

**Comment by Geksanit** [comment]
В шрифтах, заменил на rem. Отступы и размеры тоже менять? Боюсь, если везде заменить, то пиксель перфект не достижим.

**Comment by Burize** [comment]
Да, конечно. Это и есть адаптивная верстка. Щас захордкожены размеры: страница не масштабируется при изменении размера окна. Да, если ширина будет меньше 816px, то растянется на весь экран, но это не адаптив (ну или liquid - не суть) - а просто 1 условие. Сам макет не резиновый. Нужно сделать чтобы он смотрелся пропорционально для нескольких размеров экрана. Не большие расхождения с pixelperfect это нормально.

**Comment by Burize** [comment]
Вообще это основная цель этого задания (помимо реализации правильной модульности компонент) - правильно реализовать выравнивание - растяжение - позиционирование элементов через относительные величины.
