### ISSUE TITLE
percents

### ISSUE THREAD

**Issue by Burize** [Geksanit/Maket-resume#36]
https://github.com/Geksanit/Maket-resume/blob/master/frontend/components/soft/soft.pug

Сделай через стили - там можно просто ширину внутреннего блока задавать, тогда этот 1 блок будет заменять 100 дивов .soft_percent

**Comment by Geksanit** [comment]
У меня так раньше и было, но тогда через миксин в pug не получится регулировать проценты, ну или я не знаю как.

**Comment by Geksanit** [comment]
Теперь дивов не больше 19. Так лучше? Или всё же сделать один захардкоженный блок, как ты предложил?

**Comment by Burize** [comment]
Там же можно просто в миксин передать % и его задать в style: 
`div( style="width:"+percent+"%;")` - это будет внутренний блок, который синий. Он будет внутри серого блока. В итоге будет всего 2 блока. И в этом случае можно будет задавать не целые числа (хоть какие): 77.12 или 0.05 как значение.

**Comment by Geksanit** [comment]
Действительно, как я сам про это забыл )   Исправил.
