### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by Burize** [Geksanit/Maket-resume#38]
Есть 2 замечания:
- в командах в секции scripts всегда указываются локальные модули, а не установленные глобально (как сейчас указан webpack). Может показаться не существенно, но это избавляет от конфликтов при сборке, потому что у меня (ну или другого разработчика) может быть глобально установлена версия отличная от той, которая использовалась при разработке.

- devDependencies - это зависимости используемые при разработке: линтеры, dev-sever, может какие-либо типы и тд. Все остальное это обычные dependencies, которые используются при сборки продакшена.

**Comment by Geksanit** [comment]
Нужно указать запуск локального вебпака? 
"dev": "webpack --watch"    - здесь? По умолчанию запускается локальный вебпак (где-то в доках читал). Искал, может есть какие аргументы типо "--local" - ничего такого нет.
По второму замечанию исправил.

**Comment by Burize** [comment]
Есть локальные модули. Они находятся в папке node_modules проекта. А есть глобальные, которые были установлены через npm (или другой менеджер пакетов) с префиксом `-g` (они доступны везде). 
`"dev": "webpack --watch"` - запускает webpack, который установлен на компьютере глобально, а не который установлен в node_modules и имеющий версию указанную в  package.json. То есть, есть в package указан вебпак 2ой версии, а глобально установлен вебпак 3ей версии, то запуститься именно 3ая версия. 

При командной работе над большим проектом глобальные модули (webpack, karma, jest и др) у каждого разработчика будут отличаться по версии, по этому важно указывать при запуске именно тот, модуль который был загружен в node_modules с нужной версией.

**Comment by Burize** [comment]
во 2ом макете тоже нужно поправить будет

**Comment by Geksanit** [comment]
Вот так правильно?

**Comment by Burize** [comment]
Да
