### ISSUE TITLE
Длинное имя ломает верстку

### ISSUE THREAD

**Issue by shevdi** [Geksanit/Maket-resume#40]
Если ввести длинное имя или фамилию, то столбец разъезжается.

**Comment by shevdi22** [comment]
Сейчас у меня что-то поле с именем немного прикрывает белым фоном фамилию. И странно текст обрезается. Нужен или перенос на следующую строчку или хотя бы сокращение имени с тремя точками на конце

**Comment by kinda-neat** [comment]
Нужен перенос на новую строчку, сейчас у тебя там стоит одно магическое css правило, которое и делает это перекрытие)

**Comment by Geksanit** [comment]
Я понял)  word-break поможет)

**Comment by kinda-neat** [comment]
Да, теперь лучше) Можешь закрывать
