### ISSUE TITLE
Немного странные названия 

### ISSUE THREAD

**Issue by shevdi** [Geksanit/Maket-resume#42]
В целом не стоит в названиях блоков или элементов повторять дословно названия тегов. Лучше что бы название было хотя бы немного абстрактнее: вместо li-text list-text,  Вместо experience__ul experience__list. Ну, или можешь подобрать вариант, который тебе будет ближе )

И еще. Университет написан с ошибкой

**Comment by kinda-neat** [comment]
Сюда же, что за блок line? не несет никакой семантики. лучше переименовать на header
line-text на list-item

**Comment by kinda-neat** [comment]
Этот можешь закрывать
