### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by kinda-neat** [Geksanit/Maket-resume#44]
Текст Name here наезжает на surname
![2018-01-20 12-25-08](https://user-images.githubusercontent.com/27883524/35180186-0e435f58-fddd-11e7-8e73-458c9cfb4d7f.png)

**Comment by Geksanit** [comment]
хм, я не могу воспроизвести  такую ошибку. При любом размере шрифта всё выглядит норм.

**Comment by kinda-neat** [comment]
У тебя там задан overflow: hidden, совершенно ненужный, можешь объяснить зачем он?
![overflow](https://user-images.githubusercontent.com/27883524/35209942-c8c7761a-ff82-11e7-8499-a83a50dca750.gif)

**Comment by Geksanit** [comment]
Для того что бы длинное имя обрезалось, без overflow не работает text-overflow. Но text-overflow не обязателен, и без него обрезается.

**Comment by kinda-neat** [comment]
Давай продолжим этот вопрос в #40 Они связаны
