### ISSUE TITLE
Внешняя геометрия блока

### ISSUE THREAD

**Issue by kinda-neat** [Geksanit/Maket-resume#45]
Блок не должен влиять на свое окружение, т. е. блоку не следует задавать внешнюю геометрию (в виде отступов, границ, влияющих на размеры) и позиционирование. Теряется независимость, при которой возможно повторное использование или перенос блоков с места на место.
У тебя же сейчас это правило нарушается в блоках profile, contact и т.д., пройдись по всем блокам и исправь это

**Comment by kinda-neat** [comment]
Миксы плохая практика (хотя и по БЭМу), нарушают самодостаточность блока, не хорошо лезть внутрь блока извне, есть способ элегантнее в этом отношении)

**Comment by Geksanit** [comment]
Последний способ, который я знаю - это прописать в index.less стиль блока. Это будет не элегантно. А, можно же в контейнер положить блок и контейнеру добавить отступы! )

**Comment by kinda-neat** [comment]
Да, в очень правильном направлении думаешь, только вот не нужно в названии блока мешать числа, порядковые номера, этого нужно избегать
И все эти .column-left, container-first/second и т.д., разве это по БЭМ?

**Comment by Geksanit** [comment]
Назвал контейнеры по содержимому.

**Comment by kinda-neat** [comment]
А контейнер это что за сущность по БЭМу?

**Comment by Geksanit** [comment]
Контейнеры - это элементы блока.

**Comment by kinda-neat** [comment]
Еееее, вот сейчас все отлично :) Теперь пройдись и посмотри где еще такие ляпы есть
вот здесь к примеру, блоку header задана внешняя геометрия
![2018-01-27 16-57-36](https://user-images.githubusercontent.com/27883524/35471645-d0b2a49a-0391-11e8-87a7-16075f9e5f67.png)
И не забывай про второй макет и кастомные страницы :)

**Comment by Geksanit** [comment]
Прошелся, исправил.

**Comment by kinda-neat** [comment]
Миксы нужно убрать везде)
![2018-01-28 12-11-40](https://user-images.githubusercontent.com/27883524/35479212-7c21e5f6-0424-11e8-8800-822865c085d3.png)

**Comment by Geksanit** [comment]
Второй макет весь на миксах построен ) Кучу кода нужно ещё переделать )
