### ISSUE TITLE
Задание стилей

### ISSUE THREAD

**Issue by kinda-neat** [Geksanit/Maket-resume#46]
Не задавать стили через селекторы по тегу, если стилизуешь элемент, то нужно задать ему класс
![2018-01-20 12-57-52](https://user-images.githubusercontent.com/27883524/35180370-8c7afa1c-fde1-11e7-9ee5-f0b769aee978.png)

**Comment by kinda-neat** [comment]
https://ru.bem.info/methodology/css/#%D0%A1%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D1%8B
Еще раз перечитай БЭМ)

**Comment by Geksanit** [comment]
Тут вылезает наружу одна проблема, тег а со всеми атрибутами задается в неудобном месте.

**Comment by kinda-neat** [comment]
Что мешает сделать этот тег элементом и расположить в стилях на том же уровне с &__value?

**Comment by kinda-neat** [comment]
Везде посмотрел? Нигде больше не осталось таких ляпов?)

**Comment by Geksanit** [comment]
В этом макете нигде не осталось, это был единственный )
